config/routes.rb
Rails.application.routes.draw do
  resource :home, only: :show, controller: :home
  resource :about, only: :show, controller: :about

  resources :packages, only: [:show, :index]

  root "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/package.rb
class Package < ApplicationRecord
  extend FriendlyId

  STOCK_ATTRIBUTES = {
    PRIMARY_STARTER: {
      name: "3 Month Starter",
      price_cents: 40_000,
      description: "All first-time clients must book six sessions at a discounted price"
    }
  }.freeze

  @primary_starter_mutex = Mutex.new

  friendly_id :name, use: :slugged
  monetize :price_cents

  validates :name, :price_cents, presence: true
  validates :name, uniqueness: true

  def self.primary_starter
    return @primary_starter if @primary_starter

    @primary_starter_mutex.synchronize do
      @primary_starter ||= find_or_create_by!(STOCK_ATTRIBUTES[:PRIMARY_STARTER])
    end

    @primary_starter
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def index
    @package = Package.primary_starter
  end

  def show
    @package = Package.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def browser_title
    if content_for?(:browser_title)
      content_for(:browser_title)
    elsif content_for?(:browser_title_prefix)
      "#{content_for(:browser_title_prefix)} &bullet; #{t("site.title")}"
    else
      t("site.title")
    end
  end
end

app/views/about/show.html.erb
<h1><%= t("common.about").capitalize %></h1>

<p class="mt-4">
  Joe Sak is a Relationship Coach, certified by The Relationship School<sup>&reg;</sup>
  as a Level 1 Relationship Coach for Individuals.
</p>

app/views/home/show.html.erb
<svg
  class="hidden lg:block absolute right-0 inset-y-0 h-full w-48 text-white transform translate-x-1/2"
  fill="currentColor"
  viewBox="0 0 100 100"
  preserveAspectRatio="none"
  aria-hidden="true"
>
  <polygon points="50,0 100,0 50,100 0,100" />
</svg>

<div class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
  <div class="sm:text-center lg:text-left">
    <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block"><%= t(".title") %></span>
      <span class="block text-green-800"><%= t(".subtitle") %></span>
    </h1>

    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
      <%= t(".pitch") %>
    </p>

    <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
      <div class="rounded-md shadow">
        <%= link_to t("common.get_started").titleize, packages_path, class: "w-full btn" %>
      </div>
    </div>
  </div>
</div>

<% content_for :splash_image do %>
  <%= image_tag "https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80",
    alt: "",
    class: "h-56 w-full object-cover sm:h-72 md:h-96 lg:w-full lg:h-full"
  %>
<% end %>

app/views/layouts/_header.html.erb
<div data-controller="reveal">
  <div class="relative pt-6 px-4 sm:px-6 lg:px-8">
    <nav
      class="relative flex items-center justify-between sm:h-10 lg:justify-start"
      aria-label="Global"
    >
      <div class="flex items-center flex-grow flex-shrink-0 lg:flex-grow-0">
        <div class="flex items-center justify-between w-full md:w-auto">
          <%= link_to root_path do %>
            <span class="sr-only"><%= t("site.title") %></span>

            <%= image_tag "logo.jpg",
              alt: "logo",
              class: "h-8 w-auto sm:h-10 rounded-full"
            %>
          <% end %>

          <div class="-mr-2 flex items-center md:hidden">
            <button
              data-action="reveal#show"
              type="button"
              class="
                bg-white
                rounded-md
                p-2
                inline-flex
                items-center
                justify-center
                text-gray-400
                hover:text-gray-500
                hover:bg-gray-100
                focus:outline-none
                focus:ring-2
                focus:ring-inset
                focus:ring-green-500
              "
              aria-expanded="false"
            >
              <span class="sr-only">
                <%= t("common.open_main_menu").capitalize %>
              </span>
              <!-- Heroicon name: outline/menu -->
              <svg
                class="h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M4 6h16M4 12h16M4 18h16"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>

      <div class="hidden md:block md:ml-10 md:pr-4 md:space-x-8">
        <%= link_to t("common.about").capitalize,
          about_path,
          class: "font-medium text-gray-500 hover:text-gray-900" %>

        <%= link_to "Book Online", "#",
          class: "font-medium text-gray-500 hover:text-gray-900" %>

        <%= link_to t("common.package").pluralize.capitalize,
          packages_path,
          class: "font-medium text-gray-500 hover:text-gray-900" %>

        <%= link_to "Resources", "#",
          class: "font-medium text-gray-500 hover:text-gray-900" %>
      </div>
    </nav>
  </div>

  <!--
    Mobile menu, show/hide based on menu open state.

  -->
  <div
    data-reveal-target="item"
    data-transition-enter="duration-150 ease-out"
    data-transition-enter-start="opacity-0 scale-95"
    data-transition-enter-end="opacity-100 scale-100"
    data-transition-leave="duration-100 ease-in"
    data-transition-leave-start="opacity-100 scale-100"
    data-transition-leave-end="opacity-0 scale-95"
    class="absolute z-10 top-0 inset-x-0 p-2 transition transform origin-top-right hidden"
  >
    <div class="rounded-lg shadow-md bg-white ring-1 ring-black ring-opacity-5 overflow-hidden">
      <div class="px-5 pt-4 flex items-center justify-between">
        <%= link_to root_path do %>
          <%= image_tag "logo.jpg", alt: "logo", class: "h-8 w-auto rounded-full" %>
        <% end %>

        <div class="-mr-2">
          <button
            data-action="reveal#hide"
            type="button"
            class="
              bg-white
              rounded-md
              p-2
              inline-flex
              items-center
              justify-center
              text-gray-400
              hover:text-gray-500
              hover:bg-gray-100
              focus:outline-none
              focus:ring-2
              focus:ring-inset
              focus:ring-green-500
            "
          >
            <span class="sr-only">Close main menu</span>
            <!-- Heroicon name: outline/x -->
            <svg
              class="h-6 w-6"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
      </div>

      <div class="px-2 pt-2 pb-3 space-y-1">
        <%= link_to t("common.about").capitalize,
          about_path,
          class: %w[
            block
            px-3
            py-2
            rounded-md
            text-base
            font-medium
            text-gray-700
            hover:text-gray-900
            hover:bg-gray-50
          ]
        %>

        <%= link_to "Book Online", "#",
          class: %w[
            block
            px-3
            py-2
            rounded-md
            text-base
            font-medium
            text-gray-700
            hover:text-gray-900
            hover:bg-gray-50
          ]
        %>

        <%= link_to t("common.package").pluralize.capitalize,
          packages_path,
          class: %w[
            block
            px-3
            py-2
            rounded-md
            text-base
            font-medium
            text-gray-700
            hover:text-gray-900
            hover:bg-gray-50
          ]
        %>

        <%= link_to "Resources", "#",
          class: %w[
            block
            px-3
            py-2
            rounded-md
            text-base
            font-medium
            text-gray-700
            hover:text-gray-900
            hover:bg-gray-50
          ]
        %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-stone-200">
  <head>
    <title><%= browser_title.html_safe %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>

  <body>
    <div class="relative bg-white shadow overflow-hidden">
      <div class="max-w-7xl mx-auto">
        <div class="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32">
          <%= render 'layouts/header' %>
          <main class="container p-8">
            <%= yield %>
          </main>
        </div>
      </div>

      <% if content_for?(:splash_image) %>
        <div class="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
          <%= yield :splash_image %>
        </div>
      <% end %>
    </div>
  </body>
</html>